# Generated by Django 3.1.5 on 2021-01-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0002_auto_20210125_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(unique=True),
        ),
    ]
