# Generated by Django 3.1.5 on 2021-01-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0003_auto_20210125_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleword',
            name='count',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
