# Generated by Django 3.1.5 on 2021-01-26 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0006_auto_20210125_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleword',
            name='article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='words.article'),
        ),
        migrations.AlterField(
            model_name='articleword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='words.word'),
        ),
    ]
