# Generated by Django 3.1.5 on 2021-01-26 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0007_auto_20210126_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleword',
            name='content',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
