# Generated by Django 3.1.5 on 2021-01-26 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0008_articleword_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articleword',
            name='content',
        ),
    ]
