# Generated by Django 3.1.5 on 2021-01-26 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0009_remove_articleword_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleword',
            name='content',
            field=models.IntegerField(default=None),
        ),
    ]
